users:
  Owner:
    accounts:
      일반증권:
        vps: {moderate: 5000000, free: 3000000}
        prod: {moderate: 0, free: 0}
      ISA:
        prod: {moderate: 0, free: 0}
free_holdings:
  Owner:
    일반증권:
    - code: '000660'
      name: SK하이닉스
      style: free
      added_by: telegram
      confirm: Waiting
      added_date: '2026-06-28'
      dividend: 1
      sector: 전기·전자
      industry: 반도체 제조업
      note: 자유투자
    - code: 049720
      name: 고려신용정보
      style: free
      added_by: telegram
      confirm: Approval
      added_date: '2026-08-02'
      sector: ''
      industry: 신용조사 및 추심 대행업
      note: 자유투자
      buy_plan: {}
cash_plan:
  krw_ratio: 60
  krw_etfs:
  - code: '469830'
    name: SOL 초단기채권액티브
    weight: 30
  - code: '157450'
    name: TIGER 단기통안채
    weight: 40
  - code: '214980'
    name: KODEX 단기채권PLUS
    weight: 30
  usd_bond:
    code: '329750'
    name: TIGER 미국달러단기채권액티브
    enabled: false
